# Workflow name
name: Build list-detail-activity-embedding

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set Up JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Make gradlew executable
        run: chmod +x ./gradlew
        working-directory: ./CanonicalLayouts/list-detail-activity-embedding

      - name: Build list-detail-activity-embedding app
        working-directory: ./CanonicalLayouts/list-detail-activity-embedding
        run: ./gradlew :app:assembleDebug
